services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sheikh-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Alisheikh@123"
    ports:
      - "1433:1433"
    volumes:
      - sheikh-sql-data:/var/opt/mssql
volumes:
  sheikh-sql-data:
