using System.Net;
using System.Text;
using System.Text.RegularExpressions;

namespace SheikhTravelSystem.Infrastructure.Services.Notifications;

/// <summary>Placeholder replacement + SheikhGo branded HTML email shell.</summary>
public static class EmailTemplateRenderer
{
    private static readonly Regex PlaceholderRegex = new(
        @"\{\{\s*(\w+)\s*\}\}",
        RegexOptions.Compiled | RegexOptions.IgnoreCase);

    public static string ApplyPlaceholders(string? input, IReadOnlyDictionary<string, string> vars)
    {
        if (string.IsNullOrEmpty(input)) return input ?? "";

        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var kv in vars)
            map[kv.Key] = kv.Value ?? "";

        Alias(map, "Title", "title");
        Alias(map, "Message", "message");
        Alias(map, "RecipientName", "recipientName", "FullName", "UserName");
        Alias(map, "VehicleName", "vehicle", "Vehicle");
        Alias(map, "DriverName", "driver", "Driver");
        Alias(map, "DateTime", "datetime", "Timestamp", "CreatedAt");
        Alias(map, "Location", "Address", "GeoLocation");
        Alias(map, "PortalUrl", "portalUrl", "AppUrl");
        Alias(map, "CompanyName", "company");
        Alias(map, "Priority", "priority");
        Alias(map, "AlertType", "alertType", "Type");

        return PlaceholderRegex.Replace(input, m =>
        {
            var key = m.Groups[1].Value;
            return map.TryGetValue(key, out var v) ? v : "";
        });
    }

    public static bool LooksLikeUnresolvedTemplate(string? text) =>
        !string.IsNullOrWhiteSpace(text) && text.Contains("{{", StringComparison.Ordinal);

    public static bool IsHtmlDocument(string? text) =>
        !string.IsNullOrWhiteSpace(text) &&
        (text.Contains("<html", StringComparison.OrdinalIgnoreCase)
         || text.Contains("<!DOCTYPE", StringComparison.OrdinalIgnoreCase));

    public static bool LooksLikeHtmlFragment(string? text) =>
        !string.IsNullOrWhiteSpace(text) && text.Contains('<');

    /// <summary>Wrap plain or fragment content in the SheikhGo branded email layout.</summary>
    public static string WrapBranded(
        string heading,
        string bodyHtmlOrText,
        IReadOnlyDictionary<string, string> vars,
        string? accentColor = null)
    {
        var accent = accentColor ?? "#0F766E";
        var recipient = WebUtility.HtmlEncode(Get(vars, "RecipientName", "there"));
        var portal = Get(vars, "PortalUrl", "https://app.sheikhgo.com");
        var company = WebUtility.HtmlEncode(Get(vars, "CompanyName", "SheikhGo ERP"));
        var safeHeading = WebUtility.HtmlEncode(heading);

        var messageInner = LooksLikeHtmlFragment(bodyHtmlOrText)
            ? bodyHtmlOrText
            : $"<p style=\"margin:0;line-height:1.55;color:#334155;\">{WebUtility.HtmlEncode(bodyHtmlOrText)}</p>";

        var details = BuildDetailsTable(vars);

        return $"""
            <!DOCTYPE html>
            <html>
            <head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{safeHeading}</title></head>
            <body style="margin:0;padding:0;background:#f4f7fb;font-family:Segoe UI,Arial,sans-serif;">
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f7fb;padding:30px;">
            <tr><td align="center">
            <table width="650" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 4px 12px rgba(0,0,0,.08);max-width:650px;width:100%;">
              <tr>
                <td style="background:{accent};padding:25px;color:white;">
                  <h2 style="margin:0;font-size:22px;">SheikhGo ERP</h2>
                  <div style="opacity:.9;font-size:14px;margin-top:4px;">AI Fleet Operations Platform</div>
                </td>
              </tr>
              <tr>
                <td style="padding:30px;">
                  <h2 style="margin-top:0;color:{accent};">{safeHeading}</h2>
                  <p style="color:#334155;line-height:1.55;">Dear <strong>{recipient}</strong>,</p>
                  {messageInner}
                </td>
              </tr>
              {details}
              <tr>
                <td align="center" style="padding:10px 30px 28px;">
                  <a href="{WebUtility.HtmlEncode(portal)}"
                     style="background:{accent};color:white;padding:14px 28px;text-decoration:none;border-radius:6px;font-weight:600;display:inline-block;">
                    Open SheikhGo ERP
                  </a>
                </td>
              </tr>
              <tr>
                <td style="background:#f8fafc;padding:20px;font-size:13px;color:#666;text-align:center;">
                  This email was automatically generated by <strong>{company}</strong>.
                  <br><br>© {DateTime.UtcNow.Year} SheikhGo Technologies
                </td>
              </tr>
            </table>
            </td></tr></table>
            </body></html>
            """;
    }

    private static string BuildDetailsTable(IReadOnlyDictionary<string, string> vars)
    {
        var rows = new (string Label, string Key)[]
        {
            ("Vehicle", "VehicleName"),
            ("Driver", "DriverName"),
            ("Tracker", "TrackerName"),
            ("Date", "DateTime"),
            ("Location", "Location"),
            ("Speed", "Speed"),
            ("Battery", "Battery"),
            ("Fuel", "FuelLevel"),
            ("Priority", "Priority"),
            ("Alert", "AlertType")
        };

        var sb = new StringBuilder();
        var any = false;
        foreach (var (label, key) in rows)
        {
            var val = Get(vars, key);
            if (string.IsNullOrWhiteSpace(val)) continue;
            any = true;
            sb.Append($"""
                <tr>
                  <td style="padding:10px;background:#f8fafc;width:140px;"><b>{label}</b></td>
                  <td style="padding:10px;color:#0f172a;">{WebUtility.HtmlEncode(val)}</td>
                </tr>
                """);
        }

        if (!any) return "";

        return $"""
            <tr>
              <td style="padding:0 30px 20px;">
                <table width="100%" style="border-collapse:collapse;border:1px solid #e2e8f0;">
                  {sb}
                </table>
              </td>
            </tr>
            """;
    }

    private static void Alias(Dictionary<string, string> map, string primary, params string[] alts)
    {
        if (!map.TryGetValue(primary, out var primaryVal) || string.IsNullOrEmpty(primaryVal))
        {
            foreach (var a in alts)
            {
                if (map.TryGetValue(a, out var v) && !string.IsNullOrEmpty(v))
                {
                    map[primary] = v;
                    break;
                }
            }
        }

        if (map.TryGetValue(primary, out var p) && !string.IsNullOrEmpty(p))
        {
            foreach (var a in alts)
                map.TryAdd(a, p);
        }
    }

    private static string Get(IReadOnlyDictionary<string, string> vars, string key, string fallback = "")
    {
        foreach (var kv in vars)
        {
            if (string.Equals(kv.Key, key, StringComparison.OrdinalIgnoreCase) && !string.IsNullOrWhiteSpace(kv.Value))
                return kv.Value;
        }
        return fallback;
    }
}
