/* Auto-generated by scripts/export-tool-catalog.mjs — do not edit by hand */
import type { McpCatalog } from './mcp-catalog.service';

export const MCP_CATALOG_FALLBACK: McpCatalog = {
  "version": "0.5.0",
  "protocol": "MCP (stdio)",
  "package": "sheikhgo-mcp",
  "exportedAt": "2026-09-20T11:54:54.218Z",
  "discoveredTools": [
    "get_repository_index",
    "analyze_architecture",
    "list_modules",
    "analyze_module",
    "analyze_file",
    "check_architecture_rules",
    "find_similar_code",
    "suggest_implementation",
    "search_code",
    "find_dependencies",
    "get_dependency_graph",
    "analyze_impact",
    "get_git_status",
    "get_git_diff",
    "get_recent_commits",
    "architecture_decision",
    "list_architecture_decisions",
    "review_change",
    "analyze_angular",
    "analyze_flutter",
    "analyze_database",
    "find_table_usage",
    "map_feature_across_stack",
    "find_sql_usage",
    "get_database_schema",
    "get_server_info",
    "get_write_policy",
    "draft_adr",
    "scaffold_command",
    "scaffold_query",
    "write_architecture_note"
  ],
  "summary": {
    "toolCount": 31,
    "runningGroups": 2,
    "plannedGroups": 9,
    "stoppedGroups": 1
  },
  "suggestions": [
    "Analyze the Trip module",
    "Find all vehicle-related code",
    "Which vehicles need maintenance?",
    "Run all unit tests",
    "Why did build fail?",
    "Where should vehicle inspection live?"
  ],
  "quickActions": [
    {
      "id": "ask",
      "label": "Ask anything",
      "icon": "chat",
      "route": "/mcp/chat"
    },
    {
      "id": "analyze",
      "label": "Analyze code",
      "icon": "code",
      "prompt": "Analyze SheikhGo architecture for Clean Architecture violations",
      "groupId": "architecture"
    },
    {
      "id": "query",
      "label": "Query data",
      "icon": "storage",
      "prompt": "List Bookings table columns and recent SQL usage",
      "groupId": "database"
    },
    {
      "id": "fleet",
      "label": "Track fleet",
      "icon": "local_shipping",
      "prompt": "Map trips across backend, Angular, Flutter, and database",
      "groupId": "fleet"
    },
    {
      "id": "tests",
      "label": "Run tests",
      "icon": "science",
      "prompt": "What tests are missing for CreateTripCommand?",
      "groupId": "testing"
    }
  ],
  "groups": [
    {
      "id": "architecture",
      "name": "Architecture MCP",
      "description": "Understand and analyze SheikhGo architecture.",
      "icon": "account_tree",
      "status": "running",
      "tools": [
        "get_repository_index",
        "analyze_architecture",
        "list_modules",
        "analyze_module",
        "analyze_file",
        "check_architecture_rules",
        "get_dependency_graph",
        "analyze_impact",
        "architecture_decision",
        "list_architecture_decisions",
        "review_change",
        "map_feature_across_stack"
      ]
    },
    {
      "id": "code",
      "name": "Code MCP",
      "description": "Search, find and generate code across the project.",
      "icon": "code",
      "status": "running",
      "tools": [
        "search_code",
        "find_similar_code",
        "suggest_implementation",
        "find_dependencies",
        "analyze_angular",
        "analyze_flutter",
        "get_git_status",
        "get_git_diff",
        "get_recent_commits",
        "scaffold_command",
        "scaffold_query",
        "draft_adr",
        "write_architecture_note",
        "get_write_policy",
        "get_server_info"
      ]
    },
    {
      "id": "database",
      "name": "Database MCP",
      "description": "Query and analyze SQL Server database (read-only).",
      "icon": "storage",
      "status": "planned",
      "tools": [
        "analyze_database",
        "find_table_usage",
        "find_sql_usage",
        "get_database_schema"
      ],
      "note": "File-based schema analysis exists today; live SELECT-only SQL comes next."
    },
    {
      "id": "fleet",
      "name": "Fleet MCP",
      "description": "Vehicles, drivers, trips and fleet operations.",
      "icon": "local_shipping",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "get_vehicles",
        "get_drivers",
        "get_vehicle_assignments",
        "get_maintenance_records",
        "get_fuel_records"
      ]
    },
    {
      "id": "gps",
      "name": "GPS / Traccar MCP",
      "description": "Live tracking, positions and device management.",
      "icon": "gps_fixed",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "get_devices",
        "get_live_positions",
        "get_trips",
        "get_geofences",
        "get_vehicle_history"
      ]
    },
    {
      "id": "testing",
      "name": "Testing MCP",
      "description": "Run tests, check coverage and analyze test results.",
      "icon": "science",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "find_tests",
        "run_unit_tests",
        "check_test_coverage",
        "find_untested_handlers"
      ]
    },
    {
      "id": "logs",
      "name": "Logs MCP",
      "description": "Search and analyze application logs.",
      "icon": "receipt_long",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "get_errors",
        "search_logs",
        "get_slow_requests"
      ]
    },
    {
      "id": "devops",
      "name": "DevOps MCP",
      "description": "Deployments, builds and infrastructure status.",
      "icon": "cloud",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "get_deployments",
        "get_build_status",
        "get_application_health"
      ]
    },
    {
      "id": "security",
      "name": "Security MCP",
      "description": "Security analysis and vulnerability checks.",
      "icon": "security",
      "status": "stopped",
      "tools": [],
      "plannedTools": [
        "scan_authentication",
        "scan_secrets",
        "scan_api_endpoints",
        "scan_permissions"
      ],
      "note": "Not enabled in v1 — planned static analysis group."
    },
    {
      "id": "analytics",
      "name": "Analytics MCP",
      "description": "Business insights and performance metrics.",
      "icon": "insights",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "get_trip_statistics",
        "get_vehicle_utilization",
        "get_driver_performance"
      ]
    },
    {
      "id": "finance",
      "name": "Finance MCP",
      "description": "Invoices, payments and financial operations.",
      "icon": "payments",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "get_invoices",
        "get_outstanding_invoices",
        "get_revenue"
      ]
    },
    {
      "id": "crm",
      "name": "CRM MCP",
      "description": "Customers, bookings and relationship data.",
      "icon": "groups",
      "status": "planned",
      "tools": [],
      "plannedTools": [
        "get_customers",
        "get_customer_bookings",
        "get_customer_activity"
      ]
    }
  ],
  "connections": [
    {
      "id": "cursor",
      "name": "Cursor",
      "status": "unknown",
      "hint": "Add SheikhGo-MCP via config/cursor.mcp.json and reload MCP servers."
    },
    {
      "id": "claude",
      "name": "Claude Code / Desktop",
      "status": "unknown",
      "hint": "Add SheikhGo-MCP via config/claude-code.mcp.json and restart Claude."
    }
  ],
  "quickLinks": [
    {
      "label": "MCP Connections",
      "url": "/mcp/connections",
      "icon": "hub",
      "internal": true
    },
    {
      "label": "MCP Tools",
      "url": "/mcp/tools",
      "icon": "construction",
      "internal": true
    },
    {
      "label": "AI Management",
      "url": "/ai",
      "icon": "smart_toy",
      "internal": true
    }
  ]
} as McpCatalog;
