using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SheikhTravelSystem.API.Controllers;

[ApiController]
[Route("api/lookup")]
[AllowAnonymous]
public class LookupController : ControllerBase
{
    [HttpGet("timezones")]
    public IActionResult GetTimezones()
    {
        var zones = TimeZoneInfo.GetSystemTimeZones()
            .Select(tz => new { id = tz.Id, displayName = tz.DisplayName, offset = tz.BaseUtcOffset.TotalHours })
            .OrderBy(tz => tz.offset)
            .ThenBy(tz => tz.id)
            .ToList();
        return Ok(zones);
    }

    [HttpGet("currencies")]
    public IActionResult GetCurrencies() => Ok(WorldData.Currencies);

    [HttpGet("countries")]
    public IActionResult GetCountries() => Ok(WorldData.Countries);
}

internal static class WorldData
{
    internal static readonly IReadOnlyList<object> Currencies = new[]
    {
        new { code = "AED", name = "UAE Dirham" },
        new { code = "AFN", name = "Afghan Afghani" },
        new { code = "ALL", name = "Albanian Lek" },
        new { code = "AMD", name = "Armenian Dram" },
        new { code = "ANG", name = "Netherlands Antillean Guilder" },
        new { code = "AOA", name = "Angolan Kwanza" },
        new { code = "ARS", name = "Argentine Peso" },
        new { code = "AUD", name = "Australian Dollar" },
        new { code = "AWG", name = "Aruban Florin" },
        new { code = "AZN", name = "Azerbaijani Manat" },
        new { code = "BAM", name = "Bosnia-Herzegovina Convertible Mark" },
        new { code = "BBD", name = "Barbadian Dollar" },
        new { code = "BDT", name = "Bangladeshi Taka" },
        new { code = "BGN", name = "Bulgarian Lev" },
        new { code = "BHD", name = "Bahraini Dinar" },
        new { code = "BIF", name = "Burundian Franc" },
        new { code = "BMD", name = "Bermudan Dollar" },
        new { code = "BND", name = "Brunei Dollar" },
        new { code = "BOB", name = "Bolivian Boliviano" },
        new { code = "BRL", name = "Brazilian Real" },
        new { code = "BSD", name = "Bahamian Dollar" },
        new { code = "BTN", name = "Bhutanese Ngultrum" },
        new { code = "BWP", name = "Botswanan Pula" },
        new { code = "BYN", name = "Belarusian Ruble" },
        new { code = "BZD", name = "Belize Dollar" },
        new { code = "CAD", name = "Canadian Dollar" },
        new { code = "CDF", name = "Congolese Franc" },
        new { code = "CHF", name = "Swiss Franc" },
        new { code = "CLP", name = "Chilean Peso" },
        new { code = "CNY", name = "Chinese Yuan" },
        new { code = "COP", name = "Colombian Peso" },
        new { code = "CRC", name = "Costa Rican Colón" },
        new { code = "CUP", name = "Cuban Peso" },
        new { code = "CVE", name = "Cape Verdean Escudo" },
        new { code = "CZK", name = "Czech Koruna" },
        new { code = "DJF", name = "Djiboutian Franc" },
        new { code = "DKK", name = "Danish Krone" },
        new { code = "DOP", name = "Dominican Peso" },
        new { code = "DZD", name = "Algerian Dinar" },
        new { code = "EGP", name = "Egyptian Pound" },
        new { code = "ERN", name = "Eritrean Nakfa" },
        new { code = "ETB", name = "Ethiopian Birr" },
        new { code = "EUR", name = "Euro" },
        new { code = "FJD", name = "Fijian Dollar" },
        new { code = "FKP", name = "Falkland Islands Pound" },
        new { code = "GBP", name = "British Pound" },
        new { code = "GEL", name = "Georgian Lari" },
        new { code = "GHS", name = "Ghanaian Cedi" },
        new { code = "GIP", name = "Gibraltar Pound" },
        new { code = "GMD", name = "Gambian Dalasi" },
        new { code = "GNF", name = "Guinean Franc" },
        new { code = "GTQ", name = "Guatemalan Quetzal" },
        new { code = "GYD", name = "Guyanaese Dollar" },
        new { code = "HKD", name = "Hong Kong Dollar" },
        new { code = "HNL", name = "Honduran Lempira" },
        new { code = "HRK", name = "Croatian Kuna" },
        new { code = "HTG", name = "Haitian Gourde" },
        new { code = "HUF", name = "Hungarian Forint" },
        new { code = "IDR", name = "Indonesian Rupiah" },
        new { code = "ILS", name = "Israeli New Shekel" },
        new { code = "INR", name = "Indian Rupee" },
        new { code = "IQD", name = "Iraqi Dinar" },
        new { code = "IRR", name = "Iranian Rial" },
        new { code = "ISK", name = "Icelandic Króna" },
        new { code = "JMD", name = "Jamaican Dollar" },
        new { code = "JOD", name = "Jordanian Dinar" },
        new { code = "JPY", name = "Japanese Yen" },
        new { code = "KES", name = "Kenyan Shilling" },
        new { code = "KGS", name = "Kyrgystani Som" },
        new { code = "KHR", name = "Cambodian Riel" },
        new { code = "KMF", name = "Comorian Franc" },
        new { code = "KPW", name = "North Korean Won" },
        new { code = "KRW", name = "South Korean Won" },
        new { code = "KWD", name = "Kuwaiti Dinar" },
        new { code = "KYD", name = "Cayman Islands Dollar" },
        new { code = "KZT", name = "Kazakhstani Tenge" },
        new { code = "LAK", name = "Laotian Kip" },
        new { code = "LBP", name = "Lebanese Pound" },
        new { code = "LKR", name = "Sri Lankan Rupee" },
        new { code = "LRD", name = "Liberian Dollar" },
        new { code = "LSL", name = "Lesotho Loti" },
        new { code = "LYD", name = "Libyan Dinar" },
        new { code = "MAD", name = "Moroccan Dirham" },
        new { code = "MDL", name = "Moldovan Leu" },
        new { code = "MGA", name = "Malagasy Ariary" },
        new { code = "MKD", name = "Macedonian Denar" },
        new { code = "MMK", name = "Myanmar Kyat" },
        new { code = "MNT", name = "Mongolian Tugrik" },
        new { code = "MOP", name = "Macanese Pataca" },
        new { code = "MRU", name = "Mauritanian Ouguiya" },
        new { code = "MUR", name = "Mauritian Rupee" },
        new { code = "MVR", name = "Maldivian Rufiyaa" },
        new { code = "MWK", name = "Malawian Kwacha" },
        new { code = "MXN", name = "Mexican Peso" },
        new { code = "MYR", name = "Malaysian Ringgit" },
        new { code = "MZN", name = "Mozambican Metical" },
        new { code = "NAD", name = "Namibian Dollar" },
        new { code = "NGN", name = "Nigerian Naira" },
        new { code = "NIO", name = "Nicaraguan Córdoba" },
        new { code = "NOK", name = "Norwegian Krone" },
        new { code = "NPR", name = "Nepalese Rupee" },
        new { code = "NZD", name = "New Zealand Dollar" },
        new { code = "OMR", name = "Omani Rial" },
        new { code = "PAB", name = "Panamanian Balboa" },
        new { code = "PEN", name = "Peruvian Sol" },
        new { code = "PGK", name = "Papua New Guinean Kina" },
        new { code = "PHP", name = "Philippine Peso" },
        new { code = "PKR", name = "Pakistani Rupee" },
        new { code = "PLN", name = "Polish Zloty" },
        new { code = "PYG", name = "Paraguayan Guarani" },
        new { code = "QAR", name = "Qatari Rial" },
        new { code = "RON", name = "Romanian Leu" },
        new { code = "RSD", name = "Serbian Dinar" },
        new { code = "RUB", name = "Russian Ruble" },
        new { code = "RWF", name = "Rwandan Franc" },
        new { code = "SAR", name = "Saudi Riyal" },
        new { code = "SBD", name = "Solomon Islands Dollar" },
        new { code = "SCR", name = "Seychellois Rupee" },
        new { code = "SDG", name = "Sudanese Pound" },
        new { code = "SEK", name = "Swedish Krona" },
        new { code = "SGD", name = "Singapore Dollar" },
        new { code = "SHP", name = "St. Helena Pound" },
        new { code = "SLL", name = "Sierra Leonean Leone" },
        new { code = "SOS", name = "Somali Shilling" },
        new { code = "SRD", name = "Surinamese Dollar" },
        new { code = "STN", name = "São Tomé & Príncipe Dobra" },
        new { code = "SVC", name = "Salvadoran Colón" },
        new { code = "SYP", name = "Syrian Pound" },
        new { code = "SZL", name = "Swazi Lilangeni" },
        new { code = "THB", name = "Thai Baht" },
        new { code = "TJS", name = "Tajikistani Somoni" },
        new { code = "TMT", name = "Turkmenistani Manat" },
        new { code = "TND", name = "Tunisian Dinar" },
        new { code = "TOP", name = "Tongan Paʻanga" },
        new { code = "TRY", name = "Turkish Lira" },
        new { code = "TTD", name = "Trinidad & Tobago Dollar" },
        new { code = "TWD", name = "New Taiwan Dollar" },
        new { code = "TZS", name = "Tanzanian Shilling" },
        new { code = "UAH", name = "Ukrainian Hryvnia" },
        new { code = "UGX", name = "Ugandan Shilling" },
        new { code = "USD", name = "US Dollar" },
        new { code = "UYU", name = "Uruguayan Peso" },
        new { code = "UZS", name = "Uzbekistani Som" },
        new { code = "VES", name = "Venezuelan Bolívar" },
        new { code = "VND", name = "Vietnamese Dong" },
        new { code = "VUV", name = "Vanuatu Vatu" },
        new { code = "WST", name = "Samoan Tala" },
        new { code = "XAF", name = "Central African CFA Franc" },
        new { code = "XCD", name = "East Caribbean Dollar" },
        new { code = "XOF", name = "West African CFA Franc" },
        new { code = "XPF", name = "CFP Franc" },
        new { code = "YER", name = "Yemeni Rial" },
        new { code = "ZAR", name = "South African Rand" },
        new { code = "ZMW", name = "Zambian Kwacha" },
        new { code = "ZWL", name = "Zimbabwean Dollar" },
    };

    internal static readonly IReadOnlyList<object> Countries = new[]
    {
        new { name = "Afghanistan", code = "AF" },
        new { name = "Albania", code = "AL" },
        new { name = "Algeria", code = "DZ" },
        new { name = "Andorra", code = "AD" },
        new { name = "Angola", code = "AO" },
        new { name = "Antigua & Barbuda", code = "AG" },
        new { name = "Argentina", code = "AR" },
        new { name = "Armenia", code = "AM" },
        new { name = "Australia", code = "AU" },
        new { name = "Austria", code = "AT" },
        new { name = "Azerbaijan", code = "AZ" },
        new { name = "Bahamas", code = "BS" },
        new { name = "Bahrain", code = "BH" },
        new { name = "Bangladesh", code = "BD" },
        new { name = "Barbados", code = "BB" },
        new { name = "Belarus", code = "BY" },
        new { name = "Belgium", code = "BE" },
        new { name = "Belize", code = "BZ" },
        new { name = "Benin", code = "BJ" },
        new { name = "Bhutan", code = "BT" },
        new { name = "Bolivia", code = "BO" },
        new { name = "Bosnia & Herzegovina", code = "BA" },
        new { name = "Botswana", code = "BW" },
        new { name = "Brazil", code = "BR" },
        new { name = "Brunei", code = "BN" },
        new { name = "Bulgaria", code = "BG" },
        new { name = "Burkina Faso", code = "BF" },
        new { name = "Burundi", code = "BI" },
        new { name = "Cabo Verde", code = "CV" },
        new { name = "Cambodia", code = "KH" },
        new { name = "Cameroon", code = "CM" },
        new { name = "Canada", code = "CA" },
        new { name = "Central African Republic", code = "CF" },
        new { name = "Chad", code = "TD" },
        new { name = "Chile", code = "CL" },
        new { name = "China", code = "CN" },
        new { name = "Colombia", code = "CO" },
        new { name = "Comoros", code = "KM" },
        new { name = "Congo (Brazzaville)", code = "CG" },
        new { name = "Congo (Kinshasa)", code = "CD" },
        new { name = "Costa Rica", code = "CR" },
        new { name = "Croatia", code = "HR" },
        new { name = "Cuba", code = "CU" },
        new { name = "Cyprus", code = "CY" },
        new { name = "Czech Republic", code = "CZ" },
        new { name = "Denmark", code = "DK" },
        new { name = "Djibouti", code = "DJ" },
        new { name = "Dominica", code = "DM" },
        new { name = "Dominican Republic", code = "DO" },
        new { name = "Ecuador", code = "EC" },
        new { name = "Egypt", code = "EG" },
        new { name = "El Salvador", code = "SV" },
        new { name = "Equatorial Guinea", code = "GQ" },
        new { name = "Eritrea", code = "ER" },
        new { name = "Estonia", code = "EE" },
        new { name = "Eswatini", code = "SZ" },
        new { name = "Ethiopia", code = "ET" },
        new { name = "Fiji", code = "FJ" },
        new { name = "Finland", code = "FI" },
        new { name = "France", code = "FR" },
        new { name = "Gabon", code = "GA" },
        new { name = "Gambia", code = "GM" },
        new { name = "Georgia", code = "GE" },
        new { name = "Germany", code = "DE" },
        new { name = "Ghana", code = "GH" },
        new { name = "Greece", code = "GR" },
        new { name = "Grenada", code = "GD" },
        new { name = "Guatemala", code = "GT" },
        new { name = "Guinea", code = "GN" },
        new { name = "Guinea-Bissau", code = "GW" },
        new { name = "Guyana", code = "GY" },
        new { name = "Haiti", code = "HT" },
        new { name = "Honduras", code = "HN" },
        new { name = "Hungary", code = "HU" },
        new { name = "Iceland", code = "IS" },
        new { name = "India", code = "IN" },
        new { name = "Indonesia", code = "ID" },
        new { name = "Iran", code = "IR" },
        new { name = "Iraq", code = "IQ" },
        new { name = "Ireland", code = "IE" },
        new { name = "Israel", code = "IL" },
        new { name = "Italy", code = "IT" },
        new { name = "Jamaica", code = "JM" },
        new { name = "Japan", code = "JP" },
        new { name = "Jordan", code = "JO" },
        new { name = "Kazakhstan", code = "KZ" },
        new { name = "Kenya", code = "KE" },
        new { name = "Kiribati", code = "KI" },
        new { name = "Kuwait", code = "KW" },
        new { name = "Kyrgyzstan", code = "KG" },
        new { name = "Laos", code = "LA" },
        new { name = "Latvia", code = "LV" },
        new { name = "Lebanon", code = "LB" },
        new { name = "Lesotho", code = "LS" },
        new { name = "Liberia", code = "LR" },
        new { name = "Libya", code = "LY" },
        new { name = "Liechtenstein", code = "LI" },
        new { name = "Lithuania", code = "LT" },
        new { name = "Luxembourg", code = "LU" },
        new { name = "Madagascar", code = "MG" },
        new { name = "Malawi", code = "MW" },
        new { name = "Malaysia", code = "MY" },
        new { name = "Maldives", code = "MV" },
        new { name = "Mali", code = "ML" },
        new { name = "Malta", code = "MT" },
        new { name = "Marshall Islands", code = "MH" },
        new { name = "Mauritania", code = "MR" },
        new { name = "Mauritius", code = "MU" },
        new { name = "Mexico", code = "MX" },
        new { name = "Micronesia", code = "FM" },
        new { name = "Moldova", code = "MD" },
        new { name = "Monaco", code = "MC" },
        new { name = "Mongolia", code = "MN" },
        new { name = "Montenegro", code = "ME" },
        new { name = "Morocco", code = "MA" },
        new { name = "Mozambique", code = "MZ" },
        new { name = "Myanmar (Burma)", code = "MM" },
        new { name = "Namibia", code = "NA" },
        new { name = "Nauru", code = "NR" },
        new { name = "Nepal", code = "NP" },
        new { name = "Netherlands", code = "NL" },
        new { name = "New Zealand", code = "NZ" },
        new { name = "Nicaragua", code = "NI" },
        new { name = "Niger", code = "NE" },
        new { name = "Nigeria", code = "NG" },
        new { name = "North Korea", code = "KP" },
        new { name = "North Macedonia", code = "MK" },
        new { name = "Norway", code = "NO" },
        new { name = "Oman", code = "OM" },
        new { name = "Pakistan", code = "PK" },
        new { name = "Palau", code = "PW" },
        new { name = "Panama", code = "PA" },
        new { name = "Papua New Guinea", code = "PG" },
        new { name = "Paraguay", code = "PY" },
        new { name = "Peru", code = "PE" },
        new { name = "Philippines", code = "PH" },
        new { name = "Poland", code = "PL" },
        new { name = "Portugal", code = "PT" },
        new { name = "Qatar", code = "QA" },
        new { name = "Romania", code = "RO" },
        new { name = "Russia", code = "RU" },
        new { name = "Rwanda", code = "RW" },
        new { name = "Saint Kitts & Nevis", code = "KN" },
        new { name = "Saint Lucia", code = "LC" },
        new { name = "Saint Vincent & the Grenadines", code = "VC" },
        new { name = "Samoa", code = "WS" },
        new { name = "San Marino", code = "SM" },
        new { name = "São Tomé & Príncipe", code = "ST" },
        new { name = "Saudi Arabia", code = "SA" },
        new { name = "Senegal", code = "SN" },
        new { name = "Serbia", code = "RS" },
        new { name = "Seychelles", code = "SC" },
        new { name = "Sierra Leone", code = "SL" },
        new { name = "Singapore", code = "SG" },
        new { name = "Slovakia", code = "SK" },
        new { name = "Slovenia", code = "SI" },
        new { name = "Solomon Islands", code = "SB" },
        new { name = "Somalia", code = "SO" },
        new { name = "South Africa", code = "ZA" },
        new { name = "South Korea", code = "KR" },
        new { name = "South Sudan", code = "SS" },
        new { name = "Spain", code = "ES" },
        new { name = "Sri Lanka", code = "LK" },
        new { name = "Sudan", code = "SD" },
        new { name = "Suriname", code = "SR" },
        new { name = "Sweden", code = "SE" },
        new { name = "Switzerland", code = "CH" },
        new { name = "Syria", code = "SY" },
        new { name = "Taiwan", code = "TW" },
        new { name = "Tajikistan", code = "TJ" },
        new { name = "Tanzania", code = "TZ" },
        new { name = "Thailand", code = "TH" },
        new { name = "Timor-Leste", code = "TL" },
        new { name = "Togo", code = "TG" },
        new { name = "Tonga", code = "TO" },
        new { name = "Trinidad & Tobago", code = "TT" },
        new { name = "Tunisia", code = "TN" },
        new { name = "Turkey", code = "TR" },
        new { name = "Turkmenistan", code = "TM" },
        new { name = "Tuvalu", code = "TV" },
        new { name = "Uganda", code = "UG" },
        new { name = "Ukraine", code = "UA" },
        new { name = "United Arab Emirates", code = "AE" },
        new { name = "United Kingdom", code = "GB" },
        new { name = "United States", code = "US" },
        new { name = "Uruguay", code = "UY" },
        new { name = "Uzbekistan", code = "UZ" },
        new { name = "Vanuatu", code = "VU" },
        new { name = "Venezuela", code = "VE" },
        new { name = "Vietnam", code = "VN" },
        new { name = "Yemen", code = "YE" },
        new { name = "Zambia", code = "ZM" },
        new { name = "Zimbabwe", code = "ZW" },
    };
}
